apiVersion: v1
entries:
  aws-cloudwatch-logs-streamer:
  - apiVersion: v2
    appVersion: v0.0.2
    created: "2023-09-03T15:52:43.604190129+03:00"
    description: A Helm chart for AWS Cloudwatch Logs Streamer
    digest: e14d9f4a16b8960bcfa611d3fbe27186bd6cfbd28607f65c2d3e5caab98e4dfe
    name: aws-cloudwatch-logs-streamer
    type: application
    urls:
    - aws-cloudwatch-logs-streamer-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-03T15:52:43.603326818+03:00"
